import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillFacebook, AiFillTwitterCircle } from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';

import design from '../public/design.png';
import consulting from '../public/consulting.png';
import code from '../public/code.png';


import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useEffect, useState } from 'react';

const services = [
  {
    id: 1,
    name: 'Beautiful Design',
    imageUrl: design,
    description: 'Et nostrud excepteur mollit eu minim dolor mollit adipisicing.',
    tools: ['Figma', 'AdobeXD', 'illustractor']
  },
  {
    id: 2,
    name: 'Code',
    imageUrl: code,
    description: 'Et nostrud excepteur mollit eu minim dolor mollit adipisicing.',
    tools: ['React', 'JavaScript', 'Python']
  },
  {
    id: 3,
    name: 'Consulting',
    imageUrl: consulting,
    description: 'Et nostrud excepteur mollit eu minim dolor mollit adipisicing.',
    tools: ['Figma', 'AdobeXD', 'illustractor']
  },
];

const workImages = [web1, web2, web4, web6, web5, web3];


const DARKMODE_KEY = 'develop-portofolio-darkMode';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const isDarkMode = localStorage.getItem(DARKMODE_KEY);

    if (isDarkMode) {
      setDarkMode(isDarkMode);
    }
  }, []);

  const onToggleDarkMode = () => {
    setDarkMode(!darkMode);
    localStorage.setItem(DARKMODE_KEY, !darkMode);
  }

  const serviceCard = (service) => (
    <div key={service.id} className='p-8 text-center shadow-lg rounded-xl my-10 md:flex-1 dark:shadow-slate-500'>
      <Image className='m-auto' src={service.imageUrl} alt='' width={100} height={100} />
      <h3 className='text-lg pt-8 pb-2'>{service.name}</h3>
      <p className='py-2'>{service.description}</p>
      <h4 className='py-4 text-teal-600'>Design tools I use</h4>
      {service.tools.map((tool, idx) => <p key={idx} className='py-1 text-gray-600 dark:text-gray-300'>{tool}</p>)}
    </div>
  )
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Stark Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-8 md:px-16 lg:px-32 dark:bg-gray-800'>
        <section className=" min-h-screen">
          <nav className='flex justify-between py-10 dark:text-white'>
            <h1 className=' text-xl font-burtons'>DEVELOPER</h1>
            <ul className='flex items-center'>
              <li className=' cursor-pointer text-2xl' onClick={onToggleDarkMode}><BsFillMoonStarsFill /></li>
              <li><a href="#!" className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>

          <div className=' text-center p-10 dark:text-white'>
            <h2 className='text-5xl  py-2 text-teal-600 font-medium md:text-6xl'>StarkLin</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Frontend & Backend Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-600 md:text-lg md:max-w-lg md:mx-auto dark:text-gray-300'>Dolor consectetur fugiat voluptate cupidatat et consectetur deserunt proident.</p>
          </div>
          <div className='flex justify-center gap-16 py-3 text-5xl text-gray-600 dark:text-gray-300'>
            <AiFillLinkedin />
            <AiFillFacebook />
            <AiFillTwitterCircle />
          </div>
          <div className='relative mx-auto mt-16 w-80 h-80 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:w-96 md:h-96'>
            <Image className=' object-cover' src={deved} alt='deved' fill />
          </div>
        </section>

        <section>
          <div className=' dark:text-white'>
            <h3 className=' text-3xl py-1'>Services</h3>
            <p className='text-md py-2 text-gray-600 dark:text-gray-300'>
              Et nostrud excepteur mollit eu minim dolor mollit adipisicing ad quis minim duis aliquip.
              mollit eu minim dolor mollit <span className='text-teal-500'>adipisicing</span> ad quis minim duis aliquip.
            </p>
            <p className='text-md py-2 text-gray-600 dark:text-gray-300'>
              mollit eu minim dolor mollit <span className='text-teal-500'>adipisicing</span> ad quis minim duis aliquip.
            </p>
          </div>

          <div className=' md:flex md:gap-4 lg:gap-8  dark:text-white'>
            {services.map(service => serviceCard(service))}
          </div>
        </section>

        <section>
          <div className='mb-16 dark:text-white'>
            <h3 className='text-3xl py-1'>Portofolio</h3>
            <p className='text-md py-2 text-gray-600 dark:text-gray-300'>
              Et nostrud excepteur mollit eu minim dolor mollit adipisicing ad quis minim duis aliquip.
              mollit eu minim dolor mollit <span className='text-teal-500'>adipisicing</span> ad quis minim duis aliquip.
            </p>
            <p className='text-md py-2 text-gray-600 dark:text-gray-300'>
              mollit eu minim dolor mollit <span className='text-teal-500'>adipisicing</span> ad quis minim duis aliquip.
            </p>
          </div>
          <div className='mt-8 flex flex-col md:flex-row md:flex-wrap '>
            {
              workImages.map((image, idx) => (
                <div key={idx} className='p-2 flex-1 md:basis-1/2 lg:basis-1/3'>
                  <Image className=' rounded-lg object-cover' width={'100%'} src={image} alt='' />
                </div>
              ))
            }
          </div>
        </section>
      </main>
    </div>
  )
}
